# -*- coding: utf-8 -*-
"""HW-python3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-ESIgLZm9ez2AvOXnNtyKWj8-I1JtBat
"""

import numpy as np

def ES(losses, confidence=None, VaR=None, use_PnL=False):
  if VaR is None:
       if confidence is None:
        raise ValueError("Either confidence or VaR must be provided.")
       VaR = np.percentile(losses, 100 * confidence)

  extreme_losses = losses[losses > VaR]

  if len(extreme_losses) == 0:
      return VaR
  es_value = np.mean(extreme_losses)

  return es_value