# -*- coding: utf-8 -*-
"""HW-python3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-ESIgLZm9ez2AvOXnNtyKWj8-I1JtBat
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import norm

def VaR(r,confidence,principal=1):
  alpha=1-confidence
  var_threshold=np.percentile(r,alpha*100)
  out=principal*abs(var_threshold)
  return out

def percent_var(r,confidence):
  alpha=1-confidence
  var_threshold=np.percentile(r,alpha*100)

  plt.hist(r,bins=50,alpha=0.75,density=True)
  plt.show()

  out=np.percentile(r,(1-alpha)*100)
  return abs(out)