# -*- coding: utf-8 -*-
"""HW1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pWPOl89m_z8N3EbIL1BzbyzhF4V7Jrgf
"""

def WhoAmI():
  return('sx2404')

WhoAmI()