# -*- coding: utf-8 -*-
"""HW.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W3VqpcR1qHR923APnjh4Xid_DHG6DLys
"""

import yfinance as yf
import pandas as pd
import numpy as np

def YahooData2returns(YahooData):
    adj_close = YahooData['Adj Close']
    returns = adj_close.pct_change().dropna().values
    return returns

def get_stock_data(symbol):
    data = yf.download(symbol)
    prices = data['Adj Close']
    return prices

def get_returns(pricevec):
    n = len(pricevec)
    ratiovec = pricevec[1:n] / pricevec[:n-1]
    returns = ratiovec - 1
    return returns